services:
  api:
    build: .
    environment: 
      - DB_URL=postgres://user:password@db:5432/mydb?sslmode=disable 
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge