services:
  api:
    build: .
    environment: 
      - DB_URL=postgres://user:password@db:5432/gitgood-db?sslmode=disable 
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gitgood-default
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitgood-db
    ports:
      - "5432:5432"
    networks:
      - gitgood-default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gitgood-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  gitgood-default:
    driver: bridge